### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by justakim12** [justakim12/NamePadMyself#4]
## NameActivity
- [ ] Spinner에 Group data 넣기 (실패) → Spinner에 넣지 않고 Activity로 넘어가서 선택하면 그게 공란에 들어가게 하면 어떨지
- [ ] 달력에 달 시간 맞게
- [ ] editText 한줄로만 있게 (enter누르면 입력, 줄바꿈이 아니라) 
- [ ] EditText하다가 다른 곳 누르면 keyboard 사라지게
- [ ] Name 항목은 필수로 넣게 (UI에도 반영)
- [ ] Image에 이미지를 넣을 수 있도록 (스펙아웃 가능성)
- [ ] 각 항목 배열 맞추기 (sketch -> zeplin -> XML?)

## PersonListFragment
- [ ] AddNameActivity로 입력된 DB를 CustomRecyclerView로 뿌리기

## Edit
- [ ] GroupListFragment, PersonListFragment 모두 선택해서 삭제할 수 있도록
- [ ] 각 view에서 항목을 누르면 수정할 수 있는 엔드으로 이동

## Search
- [ ] Name과 Group 검색할 수 있게

## TrashCan
- [ ] 지운 항목들이 표시
- [ ] 완전 삭제 기능 추가
- [ ] 복구 기능 추가
- [ ] 일주일동안 지우지 않으면 자동 지우는 기능 추가
